codium --install-extension eamodio.gitlens
codium --install-extension esbenp.prettier-vscode
codium --install-extension foxundermoon.shell-format
codium --install-extension mads-hartmann.bash-ide-vscode
codium --install-extension ms-azuretools.vscode-docker
codium --install-extension ms-python.black-formatter
codium --install-extension ms-python.pylint
codium --install-extension ms-python.python
codium --install-extension pkief.material-icon-theme
