"$schema" = "https://starship.rs/config-schema.json"

palette = "color"
add_newline = false
format = """
[╭─](fg:gray)\
[](fg:background)[ ](bg:background)\
$directory\
$git_branch$git_commit$git_state$git_status\
[ ](bg:background)[](fg:background)\
$fill\
[](fg:background)[ ](bg:background)\
$status\
$c\
$java\
$python\
$cmd_duration\
$time\
[ ](bg:background)[](fg:background)\
$line_break\
[╰─](fg:gray)\
$character """

[directory]
format = "(fg:gray bg:background)[ $path]($style)"
truncate_to_repo = false
style = "fg:bold blue bg:background"
home_symbol = "~"
truncation_length = 8
truncation_symbol = "…/"

[git_branch]
format = "[  ](fg:gray bg:background)[$symbol $branch]($style)"
symbol = ""
style = "fg:green bg:background"
only_attached = true

[git_commit]
format = "[  ](fg:gray bg:background)[ @$hash]($style)"
style = "fg:green bg:background"
only_detached = true

[git_state]
format = "[ $state( $progress_current/$progress_total)]($style)"
style = "fg:red bg:background"

[git_status]
conflicted = "[~$count](fg:red bg:background)"
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇡$ahead_count⇣$behind_count"
up_to_date = ""
untracked = "[?$count](fg:blue bg:background)"
stashed = "[*$count](fg:green bg:background)"
modified = "!$count"
staged = "+$count"
renamed = "»$count"
deleted = "x$count"
typechanged = "t$count"
format = "[( $ahead_behind)](fg:green bg:background)[( $all_status)]($style)"
style = "fg:orange bg:background"

[fill]
symbol = " "

[status]
disabled = false
symbol = "[✘](fg:red bg:background)"
success_symbol = "[✔](fg:green bg:background)"
format = "[$symbol]($style)"
style = "fg:red bg:background"
pipestatus = true
pipestatus_format = "[$pipestatus]($style)"

[c]
symbol = ""
format = "[  ](fg:gray bg:background)[$symbol]($style)"
style = "fg:#88bbdd bg:background"

[java]
symbol = ""
format = "[  ](fg:gray bg:background)[$symbol]($style)"
style = "fg:bold yellow bg:background"

[python]
symbol = ""
format = "[  ](fg:gray bg:background)[$symbol]($style)"
style = "fg:yellow bg:background"

[cmd_duration]
format = "[  ](fg:gray bg:background)[$duration ]($style)"
style = "fg:#aaaaaa bg:background"

[time]
format = "[  ](fg:gray bg:background)[$time ]($style)"
style = "fg:#778899 bg:background"
disabled = false

[character]
format = "$symbol"
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[palettes.color]
white = "#ffffff"
yellow = "#dddd00"
orange = "#bb9922"
red = "#ff0000"
blue = "#00bbff"
green = "#66dd33"
gray = "#505050"
background = "#303030"
