finder = "rofi"

[rofi]
line_length = 100
menu_length = 10
menu_prompt = "Clipcat"
extra_arguments = ["-no-show-icons", "-i"]

[log]
emit_journald = true
emit_stdout = false
emit_stderr = false
level = "INFO"
